# List of schemas to be created
---
schemas:
  - name: "{{ lookup('env', 'PG_SERVICE_SCHEMA_SERVICE_WRITE') }}"
    owner: "{{ lookup('env', 'PGUSER') }}"
    state: present
  - name: "{{ lookup('env', 'PG_SERVICE_SCHEMA_QGIS_WRITE') }}"
    owner: "{{ lookup('env', 'PGUSER') }}"
    state: present
